/**
 * Implementer agent — generates code to satisfy the implementation plan.
 *
 * Takes the plan from the planner agent and produces working code files
 * with proper error handling, TypeScript types, and JSDoc documentation.
 * Follows the existing codebase conventions (JSDoc headers, readonly
 * interfaces, type imports, vitest test patterns).
 *
 * @module agent/implementer
 */

import { BaseAgent } from './agent.js';
import { AgentRole, type ImplementationPlan } from './types.js';
import type { GitHubBountyIssue } from '../types.js';

/**
 * A single file generated by the implementer agent.
 */
export interface GeneratedFile {
  /** File path relative to the project root. */
  readonly filePath: string;
  /** File content. */
  readonly content: string;
  /** Whether this is a new file or a modification of an existing one. */
  readonly action: 'create' | 'modify';
}

/**
 * Result of the implementation step.
 */
export interface ImplementationResult {
  /** Whether implementation was successful. */
  readonly success: boolean;
  /** Files that were generated or modified. */
  readonly files: GeneratedFile[];
  /** Error message if implementation failed. */
  readonly error: string | null;
}

/**
 * Input for the implementer agent.
 */
export interface ImplementerInput {
  /** The bounty issue being implemented. */
  readonly issue: GitHubBountyIssue;
  /** The implementation plan to follow. */
  readonly plan: ImplementationPlan;
  /** Existing codebase context (relevant files). */
  readonly codebaseContext?: string;
}

/**
 * The implementer agent generates code files based on the
 * implementation plan. It produces TypeScript code following
 * the SolFoundry SDK conventions.
 */
export class ImplementerAgent extends BaseAgent {
  readonly role = AgentRole.IMPLEMENTER;

  /**
   * Execute the implementation step.
   *
   * @param input - An ImplementerInput object.
   * @returns An ImplementationResult.
   */
  async execute(input: unknown): Promise<ImplementationResult> {
    const implInput = input as ImplementerInput;
    const files: GeneratedFile[] = [];
    const errors: string[] = [];

    for (const step of implInput.plan.steps) {
      try {
        const systemPrompt = this.buildSystemPrompt(step.files);
        const userMessage = this.buildUserMessage(implInput, step);

        const response = await this.complete(systemPrompt, userMessage, {
          maxTokens: 8192,
          temperature: 0.2,
        });

        const stepFiles = this.parseGeneratedFiles(response.content, step.files);
        files.push(...stepFiles);
      } catch (error) {
        errors.push(`Step ${step.stepNumber} (${step.description}): ${String(error)}`);
      }
    }

    return {
      success: errors.length === 0,
      files,
      error: errors.length > 0 ? errors.join('; ') : null,
    };
  }

  /**
   * Build the system prompt for code generation.
   */
  private buildSystemPrompt(targetFiles: string[]): string {
    return `You are an expert TypeScript developer implementing a SolFoundry SDK feature.

Code Generation Rules:
1. Use TypeScript with strict mode conventions.
2. Use JSDoc comments for all public APIs.
3. Use readonly interfaces for data types.
4. Use type imports (\`import type { X } from './y.js'\`).
5. Handle errors with the existing SolFoundryError/NetworkError hierarchy.
6. Export types from the module index.
7. Follow the existing codebase patterns exactly.

Output format: For each file, produce a markdown section:

\`\`\`file:path/to/file.ts
// file content here
\`\`\`

Target files: ${targetFiles.join(', ')}

Respond with ONLY the file sections, no explanation.`;
  }

  /**
   * Build the user message with bounty and plan context.
   */
  private buildUserMessage(input: ImplementerInput, step: ImplementationPlan['steps'][0]): string {
    return [
      `## Bounty: ${input.issue.title}`,
      `## Issue Body:`,
      input.issue.body,
      '',
      `## Plan Step ${step.stepNumber}: ${step.description}`,
      `## Target Files: ${step.files.join(', ')}`,
      '',
      input.codebaseContext ? `## Codebase Context:\n${input.codebaseContext}` : '',
      '',
      'Generate the implementation for this step.',
    ].join('\n');
  }

  /**
   * Parse generated files from the LLM response, extracting file sections.
   */
  private parseGeneratedFiles(response: string, expectedFiles: string[]): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Pattern: ```file:path/to/file.ts
    const fileSectionRegex = /```file:(.+?)\n([\s\S]*?)```/g;
    let match: RegExpExecArray | null;

    while ((match = fileSectionRegex.exec(response)) !== null) {
      const filePath = match[1].trim();
      const content = match[2].trim();

      if (filePath && content) {
        files.push({
          filePath,
          content,
          action: 'create',
        });
      }
    }

    // If no file sections found, treat the entire response as a single file
    if (files.length === 0 && expectedFiles.length > 0) {
      files.push({
        filePath: expectedFiles[0],
        content: response,
        action: 'create',
      });
    }

    return files;
  }
}

/**
 * Create a default implementer agent.
 *
 * @param provider - LLM provider configuration.
 * @param mockMode - Whether to use mock mode.
 * @returns A configured ImplementerAgent.
 */
export function createImplementer(
  provider: import('./types.js').LLMProviderConfig,
  mockMode: boolean = false,
): ImplementerAgent {
  return new ImplementerAgent(provider, mockMode);
}