/**
 * Core type definitions for the autonomous bounty-hunting agent system.
 *
 * These types govern the multi-LLM agent orchestration pipeline:
 * 1. **Scanning** — Discover unclaimed bounties from GitHub issues.
 * 2. **Planning** — Analyze requirements and generate a structured plan.
 * 3. **Implementation** — Generate code for each step of the plan.
 * 4. **Verification** — Run tests and validate the solution.
 * 5. **Review** — Multi-LLM review of the generated solution.
 * 6. **Submission** — Create a pull request on GitHub.
 *
 * @module agent/types
 */

import type { GitHubBountyIssue } from '../types.js';

// ---------------------------------------------------------------------------
// LLM Provider Configuration
// ---------------------------------------------------------------------------

/** Supported LLM providers for the agent system. */
export type LLMProvider =
  | 'openai'
  | 'anthropic'
  | 'google'
  | 'xai'
  | 'mistral'
  | 'deepseek'
  | 'custom';

/** Configuration for a single LLM provider. */
export interface LLMProviderConfig {
  /** Provider name. */
  readonly provider: LLMProvider;
  /** API key for the provider. */
  readonly apiKey: string;
  /** Model identifier (e.g., "gpt-4o", "claude-3-opus-20240229"). */
  readonly model: string;
  /** Optional base URL for custom/self-hosted providers. */
  readonly baseUrl?: string;
  /** Maximum tokens for the response. Defaults to 4096. */
  readonly maxTokens?: number;
  /** Temperature for the model. Defaults to 0.2 for deterministic code generation. */
  readonly temperature?: number;
}

// ---------------------------------------------------------------------------
// Agent Roles
// ---------------------------------------------------------------------------

/** Roles an agent can fulfill in the multi-agent system. */
export enum AgentRole {
  /** Scans for bounties and identifies candidates. */
  SCANNER = 'scanner',
  /** Analyzes requirements and creates a structured plan. */
  PLANNER = 'planner',
  /** Generates code to implement the plan. */
  IMPLEMENTER = 'implementer',
  /** Runs tests and verifies correctness. */
  VERIFIER = 'verifier',
  /** Reviews the solution for quality and security. */
  REVIEWER = 'reviewer',
  /** Submits the final PR. */
  SUBMITTER = 'submitter',
}

// ---------------------------------------------------------------------------
// Agent Pipeline Types
// ---------------------------------------------------------------------------

/** Status of a single agent step in the pipeline. */
export enum AgentStepStatus {
  PENDING = 'pending',
  RUNNING = 'running',
  SUCCESS = 'success',
  FAILED = 'failed',
  SKIPPED = 'skipped',
}

/** A single step in the autonomous agent pipeline. */
export interface AgentStep {
  /** Which agent role performs this step. */
  readonly role: AgentRole;
  /** Human-readable description of the step. */
  readonly description: string;
  /** Current status of the step. */
  status: AgentStepStatus;
  /** Error message if the step failed. */
  error?: string;
  /** Duration of the step in milliseconds. */
  durationMs?: number;
}

// ---------------------------------------------------------------------------
// Bounty Candidate Types
// ---------------------------------------------------------------------------

/** A bounty candidate discovered by the scanner agent. */
export interface BountyCandidate {
  /** The underlying GitHub issue. */
  readonly issue: GitHubBountyIssue;
  /** Estimated complexity (1-10). */
  complexity: number;
  /** Whether the bounty is a code task (vs. community/docs). */
  isCodeTask: boolean;
  /** Whether the bounty is already claimed by another PR. */
  isClaimed: boolean;
  /** Whether the bounty has been completed (merged PR). */
  isCompleted: boolean;
  /** Confidence score (0-1) that this is a viable bounty. */
  confidence: number;
}

// ---------------------------------------------------------------------------
// Plan Types
// ---------------------------------------------------------------------------

/** A single task step in the implementation plan. */
export interface PlanStep {
  /** Step number in the sequence. */
  readonly stepNumber: number;
  /** Description of what to implement. */
  readonly description: string;
  /** Files that need to be created or modified. */
  readonly files: string[];
  /** Estimated effort (1-5). */
  readonly effort: number;
  /** Dependencies on other step numbers. */
  readonly dependsOn: number[];
}

/** The full implementation plan generated by the planner agent. */
export interface ImplementationPlan {
  /** One-line summary of the plan. */
  readonly summary: string;
  /** Ordered list of steps to implement. */
  readonly steps: PlanStep[];
  /** Any risks or concerns identified. */
  readonly risks: string[];
  /** Estimated total effort (1-10). */
  readonly totalEffort: number;
}

// ---------------------------------------------------------------------------
// Verification Types
// ---------------------------------------------------------------------------

/** Result of running a single test suite. */
export interface TestResult {
  /** Test suite name. */
  readonly suiteName: string;
  /** Whether all tests passed. */
  readonly passed: boolean;
  /** Number of tests that passed. */
  readonly passedCount: number;
  /** Number of tests that failed. */
  readonly failedCount: number;
  /** Error messages from failed tests. */
  readonly errors: string[];
  /** Duration in milliseconds. */
  readonly durationMs: number;
}

/** Overall verification result across all test suites. */
export interface VerificationResult {
  /** Whether all verification checks passed. */
  readonly passed: boolean;
  /** Individual test results. */
  readonly testResults: TestResult[];
  /** Lint/type-check results. */
  readonly lintErrors: string[];
  /** Build result. */
  readonly buildPassed: boolean;
  /** Summary of failures (if any). */
  readonly failureSummary: string;
}

// ---------------------------------------------------------------------------
// Review Types
// ---------------------------------------------------------------------------

/** Score from a single LLM reviewer. */
export interface ReviewScore {
  /** Model name that produced this score. */
  readonly modelName: string;
  /** Overall score (0-10). */
  readonly score: number;
  /** Code quality score (0-10). */
  readonly codeQuality: number;
  /** Correctness score (0-10). */
  readonly correctness: number;
  /** Security score (0-10). */
  readonly security: number;
  /** Feedback and suggestions. */
  readonly feedback: string;
  /** Whether the review approves the submission. */
  readonly approved: boolean;
}

/** Aggregated review result from multiple LLM models. */
export interface ReviewResult {
  /** Individual scores from each model. */
  readonly scores: ReviewScore[];
  /** Average overall score across all models. */
  readonly averageScore: number;
  /** Whether the overall review is approved. */
  readonly approved: boolean;
  /** Consolidated feedback. */
  readonly consolidatedFeedback: string;
}

// ---------------------------------------------------------------------------
// PR Submission Types
// ---------------------------------------------------------------------------

/** Configuration for PR submission. */
export interface PRSubmissionConfig {
  /** GitHub owner. */
  readonly owner: string;
  /** GitHub repo. */
  readonly repo: string;
  /** Branch name for the PR. */
  readonly branchName: string;
  /** Base branch (default: "main"). */
  readonly baseBranch: string;
  /** PR title. */
  readonly title: string;
  /** PR body. */
  readonly body: string;
  /** Wallet address for bounty payment (appended to title). */
  readonly walletAddress?: string;
}

// ---------------------------------------------------------------------------
// Orchestrator Config
// ---------------------------------------------------------------------------

/**
 * Full configuration for the autonomous bounty-hunting agent.
 *
 * Controls which LLM providers are used for each agent role, the
 * scanning parameters, and the orchestration behaviour.
 */
export interface BountyHunterConfig {
  /** LLM providers for each agent role. Falls back to a shared default. */
  readonly providers: Partial<Record<AgentRole, LLMProviderConfig>>;
  /**
   * Default LLM provider used when a role-specific provider is not
   * configured. Defaults to a minimal config that must be overridden.
   */
  readonly defaultProvider: LLMProviderConfig;
  /** GitHub owner/repo to scan for bounties. */
  readonly github: {
    readonly owner: string;
    readonly repo: string;
    /** Optional GitHub token for authenticated API access. */
    readonly token?: string;
  };
  /** Wallet address appended to PR titles for bounty payment. */
  readonly walletAddress?: string;
  /** Whether to use mock LLM responses (for testing). Defaults to false. */
  readonly mockMode?: boolean;
  /** Concurrency limit for parallel agent steps. Defaults to 2. */
  readonly concurrency?: number;
  /** Maximum retries for failed steps. Defaults to 2. */
  readonly maxRetries?: number;
}

// ---------------------------------------------------------------------------
// Pipeline Result
// ---------------------------------------------------------------------------

/** Final result of the bounty-hunting pipeline. */
export interface BountyHunterResult {
  /** The bounty issue that was processed. */
  readonly issue: GitHubBountyIssue;
  /** Whether the pipeline completed successfully. */
  readonly success: boolean;
  /** Steps that were executed. */
  readonly steps: AgentStep[];
  /** The generated implementation plan. */
  readonly plan: ImplementationPlan | null;
  /** Verification result. */
  readonly verification: VerificationResult | null;
  /** Review result. */
  readonly review: ReviewResult | null;
  /** PR URL if submitted. */
  readonly prUrl: string | null;
  /** Error message if the pipeline failed. */
  readonly error: string | null;
  /** Total duration in milliseconds. */
  readonly totalDurationMs: number;
}