/**
 * Workspace and PR helpers — writes LLM-generated files to a sandbox and
 * opens a GitHub pull request.
 *
 * @module @solfoundry/auto-submit-agent/executor
 */

import type { AgentConfig } from './config.js';
import type { LLMProvider } from './llm.js';
import type { ClassifiedBounty } from './classifier.js';
import type { ImplementationPlan } from './prompts.js';

/** Result of trying to auto-submit a single bounty. */
export interface SubmissionResult {
  readonly bountyId: string;
  readonly title: string;
  readonly status: 'skipped' | 'planned' | 'implemented' | 'pr-opened' | 'error';
  readonly reason?: string;
  readonly branch?: string;
  readonly prUrl?: string;
  readonly plan?: ImplementationPlan;
}

/**
 * Run the agent on one bounty: plan, generate files, write them to the local
 * sandbox workspace, optionally push + open a PR.
 */
export async function runBounty(
  bounty: ClassifiedBounty,
  plan: ImplementationPlan,
  provider: LLMProvider,
  cfg: AgentConfig,
  workspace: string,
): Promise<SubmissionResult> {
  const branch = cfg.branchTemplate.replace('{issue_number}', String(bounty.issueNumber ?? 0));
  const filesWritten: string[] = [];

  // Generate each planned file via the LLM.
  const implementedFiles = new Set<string>();
  for (let i = 0; i < plan.files.length; i++) {
    const file = plan.files[i];
    try {
      const msgs = [{
        role: 'system',
        content: 'Senior engineer. Output ONLY complete file contents, no extra text.',
      }, {
        role: 'user',
        content: `Generate the full content for file: \`${file}\` to satisfy the bounty:
${bounty.description}`,
      }];
      const resp = await provider.chat(msgs);
      const dest = `${workspace}/${file}`;
      await writeFile(dest, resp.content);
      filesWritten.push(file);
      implementedFiles.add(file);
    } catch (err) {
      // Keep going — partial output is acceptable for a T1 bounty.
      filesWritten.push(`${file} (skipped: ${err})`);
    }
  }

  if (filesWritten.length === 0) {
    return {
      bountyId: bounty.id,
      title: bounty.title,
      status: 'error',
      reason: 'LLM generated no files',
      plan,
    };
  }

  const status: SubmissionResult['status'] = filesWritten.length === plan.files.length
    ? 'implemented'
    : 'planned';

  return {
    bountyId: bounty.id,
    title: bounty.title,
    status,
    branch,
    plan,
  };
}

/**
 * Create a pull request on GitHub.
 */
export async function openPullRequest(
  cfg: AgentConfig,
  plan: ImplementationPlan,
  branch: string,
  walletAddress?: string,
): Promise<string> {
  const title = `${plan.title}${walletAddress ? ` [${walletAddress}]` : ''}`;

  const res = await fetch(
    `https://api.github.com/repos/${cfg.targetOwner}/${cfg.targetRepo}/pulls`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': '@solfoundry/auto-submit-agent',
        Authorization: `Bearer ${cfg.githubToken ?? ''}`,
      },
      body: JSON.stringify({
        title,
        head: branch,
        base: 'main',
        body: `Auto-generated by SolFoundry Auto-Submit Agent.\n\n${plan.prDescription}\n\n- [ ] Tests added / updated`,
      }),
    },
  );
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`GitHub PR create failed ${res.status}: ${text}`);
  }
  const data = (await res.json()) as { html_url: string };
  return data.html_url ?? '';
}

/**
 * Register the submitted PR as a solution on SolFoundry via the submissions API.
 */
export async function registerSubmission(
  bountyId: string,
  prUrl: string,
  cfg: AgentConfig,
): Promise<void> {
  const res = await fetch(`${cfg.baseUrl}/api/bounties/${bountyId}/submissions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      Authorization: `Bearer ${cfg.authToken ?? ''}`,
    },
    body: JSON.stringify({
      pr_url: prUrl,
      submitted_by: 'auto-submit-agent',
      contributor_wallet: cfg.payoutWallet,
      notes: 'Auto-generated solution submitted by SolFoundry Auto-Submit Agent.',
    }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`Submission registration failed ${res.status}: ${text}`);
  }
}

// ---------------------------------------------------------------------------
// Safe file writes (creates parent directories).
// ---------------------------------------------------------------------------

async function writeFile(path: string, content: string): Promise<void> {
  const { mkdir, writeFileSync } = await import('node:fs');
  const { dirname, resolve } = await import('node:path');
  const full = resolve(path);
  mkdir(dirname(full), { recursive: true }).sync();
  writeFileSync(full, content, 'utf-8');
}
