/**
 * Pluggable LLM provider abstraction.
 *
 * The agent routes prompts to whichever LLM backend the config points to.
 * Implementations are thin wrappers so the rest of the agent stays backend-
 * agnostic.
 *
 * @module @solfoundry/auto-submit-agent/llm
 */

/** A single message in an LLM conversation. */
export type ChatMessage =
  | { role: 'system'; content: string }
  | { role: 'user'; content: string }
  | { role: 'assistant'; content: string };

/** Response from the LLM provider. */
export interface LLMResponse {
  /** Model-generated text. */
  content: string;
  /** Backend that produced the response. */
  provider: string;
  /** Model name used. */
  model: string;
  /** Tokens used (best-effort). */
  usage: { promptTokens?: number; completionTokens?: number };
}

/**
 * Generic provider capable of answering a single turn of chat.
 */
export interface LLMProvider {
  /** Human-readable provider name. */
  readonly name: string;
  /**
   * Send a chat turn and get back the model's text response.
   */
  chat(messages: ChatMessage[], model?: string): Promise<LLMResponse>;
}

/**
 * Build an LLMProvider for the given backend name.
 *
 * Backends:
 * - `claude` / `openai` / `gemini` — HTTP calls to the public REST APIs
 *   (OpenAI-compatible for Claude via LLM_BASE_URL if self-hosted).
 * - `mock` — always returns a deterministic answer; useful for tests.
 */
export function createProvider(
  backend: 'claude' | 'codex' | 'gemini' | 'openai' | 'mock' = 'claude',
  opts: { baseUrl?: string; model?: string; apiKey?: string } = {},
): LLMProvider {
  if (backend === 'mock') return new MockLLMProvider(opts.model ?? 'mock');

  return new RESTLLMProvider(backend, opts);
}

/**
 * OpenAI-compatible REST provider. Supports Anthropic (via LLM_BASE_URL),
 * OpenAI / Codex, and Gemini OpenAI-compatible endpoints.
 */
class RESTLLMProvider implements LLMProvider {
  readonly name: string;

  constructor(
    readonly backend: string,
    private readonly opts: { baseUrl?: string; model?: string; apiKey?: string },
  ) {
    this.name = backend;
  }

  async chat(messages: ChatMessage[], model?: string): Promise<LLMResponse> {
    const resolvedModel = model ?? this.opts.model ?? 'claude-3-5-sonnet-20241022';
    const url = this.resolveUrl();

    const payload = {
      model: resolvedModel,
      messages,
      max_tokens: 4096,
      temperature: 0.3,
    };

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${this.opts.apiKey ?? process.env.OPENAI_API_KEY ?? ''}`,
      },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const text = await res.text().catch(() => res.statusText);
      throw new Error(`LLM provider ${this.backend} error ${res.status}: ${text}`);
    }
    const data = (await res.json()) as {
      choices?: Array<{ message?: { content: string } }>;
      usage?: { prompt_tokens?: number; completion_tokens?: number };
      content?: Array<{ type: string; text?: string }>;
    };

    // OpenAI format
    let content = data.choices?.[0]?.message?.content ?? '';
    // Anthropic native format
    if (!content && data.content?.[0]?.type === 'text') {
      content = data.content[0].text ?? '';
    }
    if (!content) {
      throw new Error(`LLM provider ${this.backend} returned no content`);
    }

    return {
      content,
      provider: this.backend,
      model: resolvedModel,
      usage: {
        promptTokens: data.usage?.prompt_tokens,
        completionTokens: data.usage?.completion_tokens,
      },
    };
  }

  private resolveUrl(): string {
    const base = this.opts.baseUrl?.trimEnd('/') ?? '';
    // Default public API endpoints by backend
    const defaults: Record<string, string> = {
      openai: 'https://api.openai.com/v1',
      codex: 'https://api.openai.com/v1',
      claude: '',
      gemini: 'https://generativelanguage.googleapis.com/v1beta/openai',
    };
    return (base || defaults[this.backend] || '') + '/chat/completions';
  }
}

/**
 * Deterministic mock provider for unit tests.
 */
class MockLLMProvider implements LLMProvider {
  readonly name = 'mock';
  constructor(readonly model: string) {}

  async chat(_messages: ChatMessage[], _model?: string): Promise<LLMResponse> {
    return {
      content: '# README\n\nThis file was auto-generated by the MockLLMProvider.\n',
      provider: 'mock',
      model: this.model,
      usage: { promptTokens: 10, completionTokens: 12 },
    };
  }
}
