"""Multi-LLM reviewer orchestration."""

from ..models import DiffFile, ReviewConfig
from .base import LLMReviewer
from .claude import ClaudeReviewer
from .openai import OpenAIReviewer
from .gemini import GeminiReviewer


class ReviewOrchestrator:
    """Aggregates reviews from multiple LLM models into a single result."""

    def __init__(self, config: ReviewConfig):
        self.config = config
        self.reviewers: list[LLMReviewer] = self._build_reviewers()

    def _build_reviewers(self) -> list[LLMReviewer]:
        mode = self.config.mode
        if mode.value == "quick":
            return [ClaudeReviewer(self.config)]
        if mode.value == "thorough":
            return [
                ClaudeReviewer(self.config),
                OpenAIReviewer(self.config),
                GeminiReviewer(self.config),
            ]
        # standard
        return [ClaudeReviewer(self.config), OpenAIReviewer(self.config)]

    async def run(self, files: list[DiffFile], instructions: str | None = None):
        """Run all reviewers and aggregate using trimmed-mean scoring."""
        from ..models import ReviewResult, Severity

        results = []
        for reviewer in self.reviewers:
            score, findings = await reviewer.review(files, instructions)
            results.append((reviewer.name, score, findings))

        # Trimmed mean: drop highest and lowest score, average the middle
        if len(results) >= 3:
            sorted_results = sorted(results, key=lambda r: r[1])
            middle = sorted_results[1:-1]
            aggregate_score = sum(r[1] for r in middle) / len(middle)
        else:
            aggregate_score = sum(r[1] for r in results) / len(results)

        # Merge findings (dedupe by file+line+message)
        all_findings = []
        seen = set()
        for _, _, findings in results:
            for f in findings:
                key = (f.file, f.line, f.message[:80])
                if key not in seen:
                    seen.add(key)
                    all_findings.append(f)

        model_scores = {name: score for name, score, _ in results}
        summary = self._build_summary(aggregate_score, all_findings)
        return ReviewResult(
            score=round(aggregate_score, 2),
            findings=all_findings,
            summary=summary,
            model_scores=model_scores,
        )

    @staticmethod
    def _build_summary(score: float, findings) -> str:
        critical = sum(1 for f in findings if str(f.severity) == "critical")
        high = sum(1 for f in findings if str(f.severity) == "high")
        medium = sum(1 for f in findings if str(f.severity) == "medium")
        lines = [
            f"## AI Code Review — Score: **{score:.1f}/10**",
            "",
        ]
        if critical or high:
            lines.append(f"### Issues found: {critical} critical, {high} high, {medium} medium")
        else:
            lines.append("No critical or high-severity issues found.")
        lines.append("")
        lines.append("_Review generated by the SolFoundry AI Code Review GitHub App._")
        return "\n".join(lines)